@startuml er_diagram

skinparam linetype ortho

entity "Book" as Book {
  * book_id : INTEGER <<PK>>
  --
  title : TEXT
  author : TEXT
  isbn : TEXT
  year : INTEGER
  publisher : TEXT
  category : TEXT
  count : INTEGER
}

entity "Reader" as Reader {
  * reader_id : INTEGER <<PK>>
  --
  name : TEXT
  card_number : TEXT
  contact : TEXT
  status : BOOLEAN
}

entity "Librarian" as Librarian {
  * librarian_id : INTEGER <<PK>>
  --
  name : TEXT
  password : TEXT
}

entity "Reservation" as Reservation {
  * reservation_id : INTEGER <<PK>>
  * book_id : INTEGER <<FK>>
  * reader_id : INTEGER <<FK>>
  * librarian_id : INTEGER <<FK>>
  --
  reservation_date : TEXT
  status : BOOLEAN
}

entity "Fine" as Fine {
  * fine_id : INTEGER <<PK>>
  * reader_id : INTEGER <<FK>>
  --
  amount : REAL
  reason : TEXT
  status : BOOLEAN
}

' Связи между сущностями
Reader -u-|{ Reservation
Book -u-|{ Reservation
Librarian -u-|{ Reservation
Reader -u-|{ Fine

@enduml