@startuml librarian_do
start
:Открыть форму\n"добавить новую книгу";
:Ввести библиографические данные\n(название, автор, ISBN...);
:Добавить/прицепить\nизображение обложки\n(Опционально);
:Создать запись о книге;
:Добавить экземпляр(ы)\n(назначить ID экземпляров,\nстатусы);

if (Первоначальный запас\nдоступен?) then (Да)
  :Отметить экземпляр\nкак "в наличии";
else (Нет)
  :Отметить экземпляр\nкак "в ожидании";
endif

:Подтвердить и сохранить;
stop
@enduml