@startuml librarian_do

start
:Библиотекарь выбирает\n"Добавить новую книгу";

:Ввод данных книги;

if (Данные корректны?) then (да)
  :Сохранение в БД;
  :total_copies = available_copies;
  :Вывод: "Книга добавлена";
else (нет)
  :Вывод ошибки;
  :Отмена операции;
endif

stop
@enduml