@startuml reader_do
start
repeat
:Поиск книг;
:Сканировать чит. карту/\nввести ID читателя;
:Проверить статус читателя;
if (Читатель заблокирован\nили штраф > лимита?) then (Да)
  :Сообщить читателю/\nотказ в выдаче;
else (Нет)
  :Поиск запрошенной\nкниги;
  if (Книга есть\nв библиотеке?) then (Да)
    :Проверить статус;
    if (Доступна?) then (Да)
      :Создать запись о выдаче\n(дата, срок возврата);
      :Отметить экземпляр\nкак "выдан";
      :Распечатать/записать\nквитанцию;
      stop
    else (Нет)
      :Сообщить читателю/\nотказ в выдаче;
    endif
  else (Нет)
    :Сообщить читателю/\nотказ в выдаче;
  endif
endif
@enduml