@startuml reader_do

title Процесс выдачи книги

start
:Читатель запрашивает книгу;
:Система проверяет:
1. available_copies > 0
2. Статус читателя = активен
3. Нет неоплаченных штрафов;

if (Все проверки пройдены?) then (да)
  :Создание записи в таблице loans;
  :issue_date = текущая дата;
  :due_date = issue_date + 30 дней;
  :available_copies = available_copies - 1;
  :Запись сохранена;
else (нет)
  if (Нет доступных экземпляров?) then (да)
    :Сообщение: "Книга недоступна";
  elseif (Читатель заблокирован?) then (да)
    :Сообщение: "Аккаунт заблокирован";
  elseif (Есть неоплаченные штрафы?) then (да)
    :Сообщение: "Имеются неоплаченные штрафы";
  endif
  :Отказ в выдаче;
endif
stop

@enduml